### ISSUE TITLE
Linking Issues

### ISSUE THREAD

**Issue by todd1794** [sirpalee/bbcp2#1]
During the building phase of bbcp2 I get this error:

[100%] Linking CXX executable bbcp2
Undefined symbols for architecture x86_64:
  "_blosc_compress", referenced from:
      bbcp_ZCX::Process() in bbcp_ZCX.cpp.o
  "_blosc_decompress", referenced from:
      bbcp_ZCX::Process() in bbcp_ZCX.cpp.o
  "_blosc_destroy", referenced from:
      bbcp_ZCX::destroy_compressor() in bbcp_ZCX.cpp.o
  "_blosc_init", referenced from:
      bbcp_ZCX::init_compressor() in bbcp_ZCX.cpp.o
  "_blosc_set_compressor", referenced from:
      bbcp_ZCX::init_compressor() in bbcp_ZCX.cpp.o
  "_blosc_set_nthreads", referenced from:
      bbcp_ZCX::init_compressor() in bbcp_ZCX.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: **\* [bbcp2] Error 1
make[1]: **\* [CMakeFiles/bbcp2.dir/all] Error 2
make: **\* [all] Error 2

on linux and macosx.

**Comment by sirpalee** [comment]
Hey there. That happens because you didn't configure BLOCS_INCLUDE_DIR and BLOSC_STATIC_LIBRARY. These can be either passed directly to CMake, using the -D flags, or set up as environment variables.

On OSX, I didn't yet configure the build for the blosc changes. I suggest testing on Linux until I have the time to revise the build scripts for OSX and test the changes.

Other than that, it's just simply moving the blosc specific code in the CMakeLists.txt outside the Unix branch, and linking it to both OSX and Unix builds.

I guess you have the blosc headers included, so gcc finds them without the BLOSC_INCLUDE_DIR, that's why there are no compilation warnings.

**Comment by todd1794** [comment]
Strange because yes it does build and seems to find everything. 

This is what I get with the variable additions:

cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr -DBLOSC_INCLUDE_DIR:PATH=/usr/include -DBLOSC_STATIC_LIBRARY:PATH=/usr/lib CMakeLists.txt
-- Configuring done
WARNING: Target "bbcp2" requests linking to directory "/usr/lib".  Targets may link only to libraries.  CMake is dropping the item.
-- Generating done
-- Build files have been written to: /root/software/bbcp2
root@frroovlx01p:~/software/bbcp2# make
Scanning dependencies of target bbcp2
[  2%] Building CXX object CMakeFiles/bbcp2.dir/src/bbcp_Stream.cpp.o
[  5%] Building CXX object CMakeFiles/bbcp2.dir/src/bbcp_Version.cpp.o
[  8%] Building CXX object CMakeFiles/bbcp2.dir/src/bbcp_FS_Null.cpp.o
[ 11%] Building CXX object CMakeFiles/bbcp2.dir/src/bbcp_FS_Pipe.cpp.o
[ 13%] Building CXX object CMakeFiles/bbcp2.dir/src/bbcp_Timer.cpp.o
[ 16%] Building CXX object CMakeFiles/bbcp2.dir/src/bbcp_Emsg.cpp.o
[ 19%] Building CXX object CMakeFiles/bbcp2.dir/src/bbcp_Network.cpp.o
[ 22%] Building CXX object CMakeFiles/bbcp2.dir/src/bbcp_Protocol.cpp.o
[ 25%] Building CXX object CMakeFiles/bbcp2.dir/src/bbcp_IO.cpp.o
[ 27%] Building CXX object CMakeFiles/bbcp2.dir/src/bbcp_NetAddrInfo.cpp.o
[ 30%] Building CXX object CMakeFiles/bbcp2.dir/src/bbcp_C32.cpp.o
[ 33%] Building CXX object CMakeFiles/bbcp2.dir/src/bbcp_RTCopy.cpp.o
[ 36%] Building CXX object CMakeFiles/bbcp2.dir/src/bbcp_FileSpec.cpp.o
[ 38%] Building CXX object CMakeFiles/bbcp2.dir/src/bbcp_IO_Null.cpp.o
[ 41%] Building CXX object CMakeFiles/bbcp2.dir/src/bbcp_MD5.cpp.o
[ 44%] Building CXX object CMakeFiles/bbcp2.dir/src/bbcp_ProgMon.cpp.o
[ 47%] Building CXX object CMakeFiles/bbcp2.dir/src/bbcp_Node.cpp.o
[ 50%] Building CXX object CMakeFiles/bbcp2.dir/src/bbcp_File.cpp.o
[ 52%] Building CXX object CMakeFiles/bbcp2.dir/src/bbcp_Config.cpp.o
[ 55%] Building CXX object CMakeFiles/bbcp2.dir/src/bbcp_ChkSum.cpp.o
[ 58%] Building CXX object CMakeFiles/bbcp2.dir/src/bbcp_ZCX.cpp.o
[ 61%] Building CXX object CMakeFiles/bbcp2.dir/src/bbcp_NetLogger.cpp.o
[ 63%] Building CXX object CMakeFiles/bbcp2.dir/src/bbcp_Pthread.cpp.o
[ 66%] Building CXX object CMakeFiles/bbcp2.dir/src/bbcp_IO_Pipe.cpp.o
[ 69%] Building CXX object CMakeFiles/bbcp2.dir/src/bbcp_BuffPool.cpp.o
[ 72%] Building CXX object CMakeFiles/bbcp2.dir/src/bbcp_FileSystem.cpp.o
[ 75%] Building CXX object CMakeFiles/bbcp2.dir/src/bbcp.cpp.o
[ 77%] Building CXX object CMakeFiles/bbcp2.dir/src/bbcp_MD5_openssl.cpp.o
[ 80%] Building CXX object CMakeFiles/bbcp2.dir/src/bbcp_LogFile.cpp.o
[ 83%] Building CXX object CMakeFiles/bbcp2.dir/src/bbcp_Link.cpp.o
[ 86%] Building CXX object CMakeFiles/bbcp2.dir/src/bbcp_System.cpp.o
[ 88%] Building CXX object CMakeFiles/bbcp2.dir/src/bbcp_Args.cpp.o
[ 91%] Building CXX object CMakeFiles/bbcp2.dir/src/bbcp_ProcMon.cpp.o
[ 94%] Building CXX object CMakeFiles/bbcp2.dir/src/bbcp_FS_Unix.cpp.o
[ 97%] Building CXX object CMakeFiles/bbcp2.dir/src/bbcp_Set.cpp.o
[100%] Building CXX object CMakeFiles/bbcp2.dir/src/bbcp_NetAddr.cpp.o
Linking CXX executable bbcp2
CMakeFiles/bbcp2.dir/src/bbcp_ZCX.cpp.o: In function `bbcp_ZCX::Process()':
bbcp_ZCX.cpp:(.text+0x258): undefined reference to `blosc_compress'
bbcp_ZCX.cpp:(.text+0x30d): undefined reference to `blosc_decompress'
CMakeFiles/bbcp2.dir/src/bbcp_ZCX.cpp.o: In function `bbcp_ZCX::init_compressor()':
bbcp_ZCX.cpp:(.text+0x653): undefined reference to `blosc_init'
bbcp_ZCX.cpp:(.text+0x65f): undefined reference to `blosc_set_nthreads'
bbcp_ZCX.cpp:(.text+0x693): undefined reference to `blosc_set_compressor'
CMakeFiles/bbcp2.dir/src/bbcp_ZCX.cpp.o: In function `bbcp_ZCX::destroy_compressor()':
bbcp_ZCX.cpp:(.text+0x69f): undefined reference to `blosc_destroy'
collect2: error: ld returned 1 exit status
CMakeFiles/bbcp2.dir/build.make:960: recipe for target 'bbcp2' failed
make[2]: *** [bbcp2] Error 1
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/bbcp2.dir/all' failed
make[1]: *** [CMakeFiles/bbcp2.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2

root@frroovlx01p:~/software/bbcp2# ls -al /usr/include/blosc*
-rw-r--r-- 1 root root  1639 Sep  2 15:28 /usr/include/blosc-export.h
-rw-r--r-- 1 root root 16751 Sep  2 15:28 /usr/include/blosc.h

root@frroovlx01p:~/software/bbcp2# ls -al /usr/lib/libblosc.*
-rw-r--r-- 1 root root 489574 Sep  2 15:29 /usr/lib/libblosc.a
lrwxrwxrwx 1 root root     13 Sep  2 15:35 /usr/lib/libblosc.so -> libblosc.so.1
lrwxrwxrwx 1 root root     18 Sep  2 15:35 /usr/lib/libblosc.so.1 -> libblosc.so.1.11.0
-rw-r--r-- 1 root root 392080 Sep  2 15:29 /usr/lib/libblosc.so.1.11.0

**Comment by sirpalee** [comment]
BLOSC_STATIC_LIBRARY has to point to the static library itself, not to the directory where the static build of blosc exists. In your case it should be /usr/lib/libblosc.a.

**Comment by todd1794** [comment]
Worked perfect. Thank you.

**Comment by todd1794** [comment]
Just to be clear. It worked for OSX as well with this CMakeLists.txt file:

cmake_minimum_required(VERSION 2.8)

project(bbcp2)

set(EXEC_NAME bbcp2)

file(GLOB SRC src/*.cpp)

add_compile_options(-D_ALL_SOURCE -D_REENTRANT -DOO_STD -Wall -Werror -std=c++11) #-Wextra -Werror

if (APPLE)
    add_compile_options(-DMACOS)
    # right now we are using brew built libs, but adding a proper find module later on
    include_directories(/usr/local/opt/openssl/include)
elseif (UNIX) # linux, non apple unix
    add_compile_options(-Dunix -D_BSD -DLINUX)
endif ()

add_executable(${EXEC_NAME} ${SRC})

if (APPLE)
    target_link_libraries(${EXEC_NAME} pthread z crypto)
    if (NOT BLOSC_INCLUDE_DIR)
        set(BLOSC_INCLUDE_DIR $ENV{BLOSC_INCLUDE_DIR})
    endif ()
    if (NOT BLOSC_STATIC_LIBRARY)
        set(BLOSC_STATIC_LIBRARY $ENV{BLOSC_STATIC_LIBRARY})
    endif ()
    include_directories(${BLOSC_INCLUDE_DIR})
    target_link_libraries(${EXEC_NAME} pthread z crypto ${BLOSC_STATIC_LIBRARY})
endif ()

install(TARGETS ${EXEC_NAME}
        DESTINATION bin)

thank you again!
